### ISSUE TITLE
希望增加删除授权记录功能

### ISSUE THREAD

**Issue by MurasameCiallo** [FoskyM/flarum-oauth-center#18]
我最近安装了Oauth Center，发现用户每次授权登录都被写进授权记录了。
然而我并没有发现界面上有直接删除授权记录的功能，只能我进数据库手动操作。
如果授权记录不被及时删除，数据库中冗余的信息会越来越多，影响论坛运行效率。
希望您考虑增加删除用户授权记录的功能，比如授权记录达到一定数量自动删除，或者提供用户自行一键删除的按钮。

**Comment by FoskyM** [comment]
好的，了解。需要等空闲时间改进。
