### ISSUE TITLE
搭建Casdoor和Flarum OAUTH遇到了问题

### ISSUE THREAD

**Issue by Hanhan0831** [FoskyM/flarum-oauth-center#20]
授权后跳转到http://localhost:8000/callback?code=4b880d86871d7f7024a14f9be688866f0fdae850&state=
显示如下
未知的认证类型（非密码或第三方提供商）：{"type":"unknown","signinMethod":"","organization":"","username":"","password":"","name":"","firstName":"","lastName":"","gender":"","bio":"","tag":"","education":"","email":"","phone":"","affiliation":"","idCard":"","region":"","invitationCode":"","application":"","clientId":"","provider":"","code":"4b880d86871d7f7024a14f9be688866f0fdae850","state":"","redirectUri":"http://localhost:8000/callback","method":"","emailCode":"","phoneCode":"","countryCode":"","autoSignin":false,"relayState":"","samlRequest":"","samlResponse":"","captchaType":"","captchaToken":"","clientSecret":"","mfaType":"","passcode":"","recoveryCode":"","plan":"","pricing":"","faceId":null}

可以支持付费解决问题吗！还有一些项目想要开发！

**Comment by FoskyM** [comment]
对 Casdoor 不太了解
