### ISSUE TITLE
能提供一份更加详细的文档吗

### ISSUE THREAD

**Issue by LiteCat0905** [FoskyM/flarum-oauth-center#4]
你好！我之前联络过你或许你还记得，我看到你加入了更多样例图片 我似乎已经知道如何使用，但我仍然不明白这个权限部分需要填写什么，我建议作者可以做一个在线文档当作教程🤔 很多设置小白都没有看懂（

**Comment by FoskyM** [comment]
最近事比较多，没精力维护项目。
或许在下一次无法预期的更新时，我会弄好文档。

**Comment by LiteCat0905** [comment]
做的好！
